- run_tests.py
- tests/__init__.py
- tests/utilities_test.py
Change run_tests.py to look for tests in the "tests" subdir, and to
find unittests as well as doctests.
> Test runner: Add a "tests" subdir with an example unittest test case

- examples/3zone_toy/solve.py
- examples/copperplate0/solve.py
- examples/copperplate1/solve.py
- examples/custom_extension/solve.py
- examples/discrete_build/solve.py
- examples/production_cost_models/1plant/solve.py
- examples/production_cost_models/3plants/solve.py
- examples/production_cost_models/4plants/solve.py
- examples/production_cost_models/discrete_unit_commit/solve.py
- examples/production_cost_models/unit_commit/solve.py
- switch_mod/utilities.py
This makes the examples runnable using only open source software --
since GLPK is open source (whereas CPLEX is proprietary).
Also move the choice of solver to one place in switch_mod, so that it
can be changed more easily.
> Change solve.py examples to use the GLPK solver instead of CPLEX

- switch_mod/fuel_cost.py
- switch_mod/fuel_markets.py
- switch_mod/gen_tech.py
- switch_mod/project/build.py
- switch_mod/project/dispatch.py
- switch_mod/project/no_commit.py
- switch_mod/project/unitcommit/fuel_use.py
- switch_mod/utilities.py
This adds elements to allow plants to switch freely among a list of fuels. If multi-fuel data are not provided, it runs the same as before. The main difference is that ProjFuelUseRate is now indexed over the available fuels (in addition to project and timepoint), and the Btu consumed by the plant during that timepoint must equal the sum of this variable across all fuels (instead of the single value of this variable).
There are also one or two other minor changes which could have been pushed separately but weren't.
This code has been used extensively in Switch-Hawaii and works well. I can submit some testing code if needed. I'd like to merge this to the master branch now to simplify life for our users (so they don't have to use the "multi-fuel" branch). But the changes are significant and …
> Adding multi-fuel capability for power plants

- switch_mod/solve.py
Avoid printing a Python traceback.
This is to address your review comment from https://github.com/switch-model/switch/pull/10.
> Print a cleaner error if the "modules" input file doesn't exist

- switch_mod/utilities.py
The same copying is done earlier in the function.
> Cleanup: De-duplicate copying of optional_params in load_aug()

- switch_mod/trans_build.py
- switch_mod/trans_dispatch.py
-Generation of the LZ_TXNet Pyomo Expression was taking a long time, so it is replaced with a simpler expression that requires the construction of an additional Set in the trans_build module. Overall, expression construction time is reduced dramatically.
-Allowed existing Tx capacity to take a value of 0, since proposed lines do not yet exist and the model may choose or not to build them in the future. Since SWITCH takes a linear (and not binary) approach to Tx line building, then initial values of 0 are required for new lines.
I was experimenting with an input set of 1 day with hourly operations each year, for 6 periods of 5 years each (720 tps), with 190 projects, 5 possible projects, 23 load zones and 32 transmission lines. The whole solve was taking 395 s on my machine with Gurobi. By …
> Speeding up transmission expression construction. Also allowing new lines to have 0 initial capacity.

- pip_requirements.txt
All the other existing dependencies are version-pinned to ensure
reproducibility, so make the recently-added dependency on sympy be
version-pinned too for the same reason and for consistency.
> Make the dependency on sympy be a version-pinned dependency

- switch_mod/balancing_areas.py
- switch_mod/fuel_cost.py
- switch_mod/fuel_markets.py
- switch_mod/trans_build.py
Use load_aug() from switch_mod.utilities to deal with optional files instead of wrapping the standard DataPortal load() function with a "if os.path.isfile(): ..."
Really, just avoid using load() for any .tab file.
> Use load_aug() from switch_mod.utilities to deal with optional files

- switch_mod/fuel_cost.py
- switch_mod/project/dispatch.py
The Fuel_Costs_TP Expression in the fuel_cost module is taking significant time to be constructed. By building and using a new Set, this process can be sped up.
For the same input set used in my last commit (23 lz, 720 tp, 190 proj, 32 tx lines) building the Fuel_Costs_TP Expression was taking 7,76 s and the whole load_inputs function was at 71,04 s.
With these changes, the Expression construction takes 1,64 s and the load_inputs function takes 68,63 s.
Model instantiation is sped up only slightly (because the Expression akes less time to build, but a new Set has to be constructed), but I believe it may become more significant in larger models, specially with more timepoints.
> Fuel_Costs_TP Expression speedup

- switch_mod/utilities.py
Previously, if the first or second lines were empty, the whole of the
file was skipped (for files loaded with optional=True), even if more
lines were present.
Instead, only skip the file if it contains 0 or 1 lines.  Validate the
headings if they are present.
> Make the handling of empty .tab files a bit stricter

- examples/custom_extension/sunk_costs.py
- switch_mod/__init__.py
- switch_mod/export/__init__.py
- switch_mod/export/dump.py
- switch_mod/export/example_export.py
- switch_mod/generators/storage.py
- switch_mod/load_zones.py
- switch_mod/project/dispatch.py
- switch_mod/solve.py
- switch_mod/utilities.py
- Removed the save_results and _save_results functions for exclusive
use of the post_solve function. Replaced the latter in all modules
which were still using save_results. This eliminates several redundancies.
- Since most new Switch users are also new Pyomo users, there is a very
slim chance that they will be using old Pyomo versions, so I didn't import some snippet of code from save_results into post_solve which was supporting them.
Since there were no checks for solver termination conditions and only
a print statement, I put a generic printing of the condition on the
solve module, if verbose option is on.
- Added an option for sorted output of generic variables. The capacity
was already written, but no command line option was available.
Passes the tests and gives me the same output as …
> Standarizing the way Switch writes output.

- switch_mod/solve.py
When either of those tools are used, solve.py isn't the top-level executable, so __name__ refers to the profiling module rather than switch_mod.solve, and the program crashes at a random spot because command-line option parsing breaks down.
Also, make the call to switch_mod.utilities less ambiguous so this module can be more portable and custom copies could live in arbitary directories.
> Make solve.py play nice with line_profiler and memory_profiler.

- examples/3zone_toy_stochastic_PySP/PySPInputGenerator.py
- examples/3zone_toy_stochastic_PySP/README.md
- switch_mod/export/__init__.py
- switch_mod/utilities.py
Default behavior is to print without sorting, to prioritize speed.
This option is extremely useful for visual inspection when developing new code or testing datasets, specially when combined with a nice diff tool.
> Add command line option to allow sorted output printing.

- examples/discrete_and_min_build/inputs/modules.txt
- switch_mod/load_zones.py
- switch_mod/local_td.py
- switch_mod/project/build.py
* Removed dangling reference to project.min_build
* Moved peak coincident load from local_td to load_zones so it could be available to more modules.
* Use system-wide non-coincident peak load as a basis for binary constraints on capacity. Using an overly large number like cumulative system-wide energy from the entire study horizon was producing errors in how glpk handled the constraint that enforces a binary decision.
> Fix to the min-build bugs from pull request #63.

- switch_mod/export/__init__.py
- switch_mod/solve.py
I  tightened the patch on `Expression.construct()` so it only applies to Pyomo 4.2 and 4.3. The corresponding bug has been fixed in Pyomo 4.4. 
I also changed string formatting to use `.format()` instead of `%` throughout solve.py. `%` should not be used in new code, since it will not work with Python 3.
I also changed the _save_generic_results() code to allow non-indexed (single-value) variables, which exist in some of my models.
> minor fixes to solve and export modules

- switch_mod/generators/storage.py
- switch_mod/project/build.py
- switch_mod/project/no_commit.py
- switch_mod/project/unitcommit/fuel_use.py
- switch_mod/solve.py
- switch_mod/timescales.py
These commits do the following:
- rename `m.proj_end_year` to `m.proj_final_period` to clarify which year it refers to (also slightly improve the calculation, e.g., using `m.period_start + m.period_length_years` instead of `m.period_end`, because `m.period_end` could refer either to the last full year of the period or the moment when the period ends (the start of the next period)
- provide post-mortem debugging, activated via a `--debug` flag
- allow single-point heat rate curves  in `project.unitcommit.fuel_use` (e.g., a plant that always produces exactly 8 MW if it is committed); a few minor bug fixes and refactorings in this code
- remove `m.DispatchProjByFuel` from `project.no_commit` module because it cannot be generalized neatly for models that use `project.unitcommit`. Note: this …
> More minor fixes

- switch_mod/hawaii/batteries_fixed_calendar_life.py
- switch_mod/hawaii/demand_response.py
- switch_mod/hawaii/demand_response_no_reserves.py
- switch_mod/hawaii/fuel_markets_expansion.py
- switch_mod/hawaii/hydrogen.py
- switch_mod/hawaii/kalaeloa.py
- switch_mod/hawaii/lng_conversion.py
- switch_mod/hawaii/no_onshore_wind.py
- switch_mod/hawaii/psip.py
- switch_mod/hawaii/r_demand_system.py
- switch_mod/hawaii/reserves.py
- switch_mod/hawaii/rps.py
- switch_mod/hawaii/scenario_data.py
This branch includes numerous changes to the `hawaii` regional package:
- update the demand response code to leave the model in a solved state, to support reporting via the `post_solve` callback
- allow automatic selection of fuel market expansion projects based on fixed cost and lifespan (e.g., find the best LNG plan that is paid off before 2045)
- `hawaii.scenario_data` has major changes to support a more streamlined back-end database (all new and existing projects in a single set of tables, created by standardized code), and to generate part load heat rate curves
- various other bug fixes and tweaks
This should be merged after the `minor_fixes` branch. Other than a merge from that branch, this branch only changes the `hawaii` package. All standard tests pass.
> SWITCH-Hawaii fixes

- INSTALL
- README
- examples/3zone_toy/README.md
- examples/copperplate0/README.md
- examples/copperplate1/README.md
- examples/discrete_and_min_build/README.md
- examples/discrete_build/README.md
- examples/hydro_simple/README.md
- examples/hydro_system/README.md
- examples/new_builds_only/README.md
- examples/production_cost_models/1plant/README.md
- examples/production_cost_models/3plants/README.md
- examples/production_cost_models/4plants/README.md
- examples/production_cost_models/discrete_unit_commit/README.md
- examples/production_cost_models/unit_commit/README.md
- examples/storage/README.md
- requirements.txt
- setup.py
- switch_mod/hawaii/constant_elasticity_demand_system.py
- switch_mod/hawaii/demand_response.py
- switch_mod/hawaii/r_demand_system.py
- switch_mod/hawaii/scenario_data.py
- switch_mod/solve_scenarios.py
Updated installation instructions to use setuptools, and usage instructions to use the switch command line script.
Added dependencies and extras to setup.py, set minimal Pyomo version to the glpk bugfix, updated entry_points syntax, implemented pointers from https://packaging.python.org/distributing/
Renamed pip_requirements.txt to requirements.txt to reflect standard python naming conventions.
> Use setuptools and switch command line tool

- switch_mod/generators/core/dispatch.py
- switch_mod/policies/rps_simple.py
Replaced PROJ_ACTIVE_PERIODS with PROJ_ACTIVE_TIMEPOINTS_IN_PERIOD to simplify end-uses in rps_simple. Replaced the internal ACTIVE_PROJ_PERIODS set with a private function.
> Streamline dispatch sets

- switch_model/policies/carbon_policies.py
Added test for existence of key in get_row in carbon_policies.py to avoid error message when key did not exist and using a social cost of carbon.  Fix suggested by Josiah Johnston.
> fix reporting for carbon_policies.py
